### ISSUE TITLE
设置imageView模式 点击图片会出现闪烁

### ISSUE THREAD

**Issue by dkdsj** [LuKane/KNPhotoBrowser#19]
RT： 真机测试出现 模拟器没有出现

设置scrollView上的imageView

imageView.contentMode = UIViewContentModeScaleAspectFit;

点击图片会出现闪烁

**Comment by LuKane** [comment]
多谢提醒! 目前问题已经修复
在KNPhotoBrowser.m文件中的 380行 将 [tempView setContentMode:sourceView.contentMode];注释掉即可
