### ISSUE TITLE
KNPhotoDownloadManager.m文件丢失

### ISSUE THREAD

**Issue by Meliny001** [LuKane/KNPhotoBrowser#20]
KNPhotoDownloadManager.m文件丢失

**Comment by LuKane** [comment]
先不要这个。这块功能还没写完，预计下周写完。若需要视频下载功能，只能等下周了------------------ 原始邮件 ------------------
发件人: "Magic"<notifications@github.com>
发送时间: 2019年7月26日(星期五) 下午2:48
收件人: "LuKane/KNPhotoBrowser"<KNPhotoBrowser@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [LuKane/KNPhotoBrowser] KNPhotoDownloadManager.m文件丢失 (#20)



KNPhotoDownloadManager.m文&#x4EF6;丢失
 
&mdash;

**Comment by LuKane** [comment]
已完成
