### ISSUE TITLE
iOS 13 "statusBar" crash问题

### ISSUE THREAD

**Issue by ChaoYug** [LuKane/KNPhotoBrowser#21]
UIView *statusBar = [[UIApplication sharedApplication] valueForKey:@"statusBar"];
在iOS 13会导致crash,需要做适配处理,处理方法可供参考

    if (@available(iOS 13.0, *))
    {
        UIWindow *statusBar = [UIApplication sharedApplication].keyWindow;

        UIView *statusView = [[UIView alloc]initWithFrame:statusBar.windowScene.statusBarManager.statusBarFrame];
                
        [UIView animateWithDuration:0.15 animations:^{
            statusView.transform = CGAffineTransformIdentity;
        }];
    }
    else
    {
        UIView *statusBar = [[UIApplication sharedApplication] valueForKey:@"statusBar"];
        
        [UIView animateWithDuration:0.15 animations:^{
            statusBar.transform = CGAffineTransformIdentity;
        }];
    }

**Comment by LuKane** [comment]
OK ,多谢!

**Comment by LuKane** [comment]
您写的代码有误
UIView *statusView = [[UIView alloc]initWithFrame:statusBar.windowScene.statusBarManager.statusBarFrame];
这是一个新的 View
