### ISSUE TITLE
消失的位置

### ISSUE THREAD

**Issue by sunlight2728** [LuKane/KNPhotoBrowser#22]
请把消失的位置 用 delegate 返回来呗
有时候可以处理一些 围绕 位置 的事件

**Comment by sunlight2728** [comment]
比如在1号位置点开图片
我在7号位置退出
tableview滑动到7号位置

**Comment by sunlight2728** [comment]
- (void)photoBrowserWillDismissWithAnimated:(UIImageView *)tempView items:(KNPhotoItems *)items{

-(void)photoBrowserWillDismiss:(NSInteger)index

**Comment by LuKane** [comment]
明天看看吧~ 可能单独给你加代码~ 但这个框架估计不会动!

**Comment by LuKane** [comment]
请留下你的联系方式~ 邮箱或者其他什么的

**Comment by LuKane** [comment]
我这边增加一个新的 Demo, 你查看下, 是不是你要的效果
