### ISSUE TITLE
关于依赖的建议

### ISSUE THREAD

**Issue by chenzhenhu** [LuKane/KNPhotoBrowser#23]
能不能把依赖三方的版本号去掉，或者使用其他标识符，现在你这个依赖会和项目依赖有版本冲突。
还有 FLAnimatedImage 这个库我相信许多项目都会依赖，而你直接复制文件到你的项目，这个很容易引起依赖你这个组建的项目编译错误

**Comment by LuKane** [comment]
1. 去掉SDWebImage版本号, 可以
2. FLAnimatedImage 这个控件, 计划自己复制一遍作者的代码!
预计明天完成
