### ISSUE TITLE
图片显示有问题

### ISSUE THREAD

**Issue by burning-git** [LuKane/KNPhotoBrowser#25]
<img width="811" alt="图片" src="https://user-images.githubusercontent.com/8384858/85864116-abc6ed00-b7f6-11ea-81de-21e8a3dcb34f.png">
    [pauseImgView setImage:[UIImage imageNamed:@"KNPhotoBrowser.bundle/playCenter@2x.png"]];
这里应该是：
    [pauseImgView setImage:[UIImage imageNamed:@"KNPhotoBrowser.bundle/playCenter"]]; 
不然适配不了3@x 图

**Comment by LuKane** [comment]
好的! ,多谢~
