### ISSUE TITLE
大佬，类似今日头条那种九宫格长图浏览效果应该怎么实现呢？

### ISSUE THREAD

**Issue by zhangxiongwen** [LuKane/KNPhotoBrowser#26]
大佬，类似今日头条那种长图浏览效果应该怎么实现呢？就是如果是长图，在九宫格内显示的时候，不是直接setContentMode 而是把图从顶部开始显示，多余的部分裁剪掉

**Comment by LuKane** [comment]
长图情况下, 只显示 长图顶部, 其他部分裁剪, 那么得对imageView单独做处理!!! 
例如: imageView是一个 正方形
imageView.layer.contentsRect = CGRectMake(0, 0, width, height);
width : 代表宽度 比率 
height: 代表高度 比率
如果你的图片是 宽:900, 高:1800
那么imageView上面, width: 可以设置成 1,  height: 可以设置成 0.5
这样的效果:  图片显示 宽度 900, 高度为原来的 1800 * 0.5 = 900
