### ISSUE TITLE
希望作者提供自定义导航栏、底部工具栏的api出来

### ISSUE THREAD

**Issue by lxm1799** [LuKane/KNPhotoBrowser#29]

**Comment by lxm1799** [comment]
哦，原来已经提供了自定义功能，不好意思。项目写的不错，谢谢作者。

**Comment by LuKane** [comment]
😁😁😁

**Comment by lxm1799** [comment]
关于KNPhotoBrowser库，我刚刚发送了一个含有视频的文件到你QQ邮箱去了，目前还没有具体定位到问题。



在 2020-09-14 14:27:35，"LuKane" <notifications@github.com> 写道：

😁😁😁

**Comment by LuKane** [comment]
我在Demo中测试没发现这方面的问题

**Comment by LuKane** [comment]
你这边将 SDAnimatedImageView 改成 KNAnimatedImageView  , 就可以了

**Comment by lxm1799** [comment]
我这边是在浏览大图的时候出现的问题。2种情况：
1是上传格式设置问题
2是框架加载图片的问题

经过这些天的调试发现，2种情况都存在。
经过修改上传格式，调整参数，使用KN浏览ok了。
之前使用的YB浏览库没有出现过这个问题。
另外：我更喜欢使用KN，这个库写的很ok，简单自用，容易自定义




| |
博览己用
|
|
邮箱：goodlucky1130@163.com
|

签名由 网易邮箱大师 定制

在2020年09月24日 18:17，LuKane 写道：

你这边将 SDAnimatedImageView 改成 KNAnimatedImageView , 就可以了
