### ISSUE TITLE
手滑消失的效果能否做出今日头条和微博一样

### ISSUE THREAD

**Issue by jianjianhao** [LuKane/KNPhotoBrowser#30]
我看了下微博和今日头条的效果是，手滑消失时自定义的和页码是会一起消失的，但是好像作者的框架手滑消失的时候头部和自定义的view还在的，怎么弄才能到达效果

**Comment by LuKane** [comment]
源代码已经更新, pod 暂时没更新

**Comment by LuKane** [comment]
pod 已更新
