### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by zhangjiangping** [LuKane/KNPhotoBrowser#33]
可不可以支持播放一次后，再次播放的时候直接从沙盒中去取资源本地播放，现在是每次播放都是进行的网络播放。

**Comment by LuKane** [comment]
微信和微博做的是: 将 数据存在 沙盒里, 它们的框架是 针对 项目做的! 
我这边不会这么做, 若这么做,就相当于 入侵式的框架了!

**Comment by LuKane** [comment]
您这边若觉得需要这个需求, 可以直接在源代码里 进行修改就好!
