### ISSUE TITLE
本地gif显示不出来

### ISSUE THREAD

**Issue by lxm1799** [LuKane/KNPhotoBrowser#36]
相关问题Demo,可前往下载：https://github.com/lxm1799/KNBrowserDemo

**Comment by lxm1799** [comment]
`
QYLocalCloudModel *model = obj;
KNPhotoItems *items = [[KNPhotoItems alloc] init];
       
            if (model.type == MediaUploadTypeVideo) {
                items.url = model.filePath;
                items.isVideo = YES;
            }else{
                items.sourceImage = (UIImage *)model.image;
            }
            [itemArr addObject:items];

//当前的model.image的类型是UIAnimatedImage，且确定是有数据的。但是赋值给items.sourceImage预览的时候黑屏。
//目前仅gif出现黑屏问题，
`

**Comment by lxm1799** [comment]
相关问题demo，可前往https://github.com/lxm1799/KNBrowserDemo下载，展示问题的demo在“AddImageViewController”

**Comment by LuKane** [comment]
不支持 本地gif图展示!

**Comment by lxm1799** [comment]
这个问题我本地修复了，相关代码晚点提交给你看看。

**Comment by LuKane** [comment]
好的!! 多谢了哈
