### ISSUE TITLE
视频播放时操作底部工具栏滑动快进条，手势会被识别为关闭浏览或者进入后台。

### ISSUE THREAD

**Issue by lxm1799** [LuKane/KNPhotoBrowser#40]
点击视频播放的时候，操作底部工具栏，滚动快进条会出现手势识别错误问题，导致视频浏览关闭或者app进入后台。
目前发现iphoneX系列机型会100%出现。

**Comment by lxm1799** [comment]
个人猜测是，底部工具位置与iphoneX底部手势操作产生了冲突。
解决办法：应该是位置调整下就行。（可以不同机型适配下）

**Comment by LuKane** [comment]
OK! 回头我修改修改! 预计周六完成

**Comment by LuKane** [comment]
pod 已更新 : 2.3.3
