### ISSUE TITLE
图片长按内部响应了右上角按钮的action

### ISSUE THREAD

**Issue by Asshasahole** [LuKane/KNPhotoBrowser#41]
KNPhotoBrowser.m  line1110
```
/**
 longPress Did click
 */
- (void)longPressIBAction{
    if(!_isNeedPictureLongPress) return;
    [self operationBtnIBAction];
}
```
现在长按根本不走长按的代理

**Comment by LuKane** [comment]
无论走哪个方法: 
长按或者右上角 点击 按钮都会 走  photoBrowserRightOperationAction 这个代理方法

如果需要进行区分, 则可自定义 控件 : CustomViewController 这个控制器中有详细Demo

**Comment by Asshasahole** [comment]
- (void)photoBrowser:(KNPhotoBrowser *)photoBrowser videoLongPress:(UILongPressGestureRecognizer *)longPress;

看下这个代理哪里会调用

**Comment by LuKane** [comment]
新的Demo中 提供了新的代理方法!  图片长按和 视频长按 走不同的代理

**Comment by LuKane** [comment]
-(void)photoBrowser:(KNPhotoBrowser *)photoBrowser videoLongPress:(UILongPressGestureRecognizer *)longPress;
这个是 当前为视频 , 而不是图片的情况下, 长按走的代理

**Comment by Asshasahole** [comment]
知道了, 我上周用的时候, 这个方法还是- (void)photoBrowser:(KNPhotoBrowser *)photoBrowser longPress:(UILongPressGestureRecognizer *)longPress;  所以以为图片和视频都会走这个方法.

**Comment by LuKane** [comment]
今天上传了最新的包, 已经区分开了 , 使用时记得 区分一下
