### ISSUE TITLE
present可能导致无法正确展示

### ISSUE THREAD

**Issue by Asshasahole** [LuKane/KNPhotoBrowser#43]
```
- (void)present{
    UIWindow *window = [UIApplication sharedApplication].keyWindow;
    [window.rootViewController presentViewController:self animated:false completion:^{
        
    }];
}
```
如果 A -> B -> photoBrowser, 如果A -> B是通过present方式跳转的(full screen), 那么在B页面查看view hierarchy, 发现里边内容是[window, B], 并没有A. 于是这里使用keyWindow的rootViewController也就是A去进行present, 就会无反应并提示:
```
We couldn’t find any repositories matching 'Attempt to present <KNPhotoBrowser: 0x11216ce00> on <RootViewController: 0x112834c00> whose view is not in the window hierarchy!'
```

我直接用`[B presentViewController:photoBrower animated:YES completion:nil];`进行展示躲过这个问题.

**Comment by LuKane** [comment]
pod 已经更新, 可以直接 [B presentViewController:photoBrower animated:YES completion:nil];
也可以 [photoBrowser present:B];
