### ISSUE TITLE
图片contentMode未设置

### ISSUE THREAD

**Issue by zhangxiongwen** [LuKane/KNPhotoBrowser#44]
demo中九宫格图片显示没有设置图片的contentMode, 一般情况下都会设置UIViewContentModeScaleAspectFill并裁剪,但是在显示预览的时候[tempView setContentMode:sourceView.contentMode];为啥被注释了呢，然后在dismiss的时候 也应该设置[tempView setContentMode:items.sourceView.contentMode];

**Comment by LuKane** [comment]
这个问题! 我找时间解决一下! 多谢

**Comment by LuKane** [comment]
我看了一下代码! 发现一个问题... 如果在九宫格中设置 contentMode, 可photoBrowser 并没有修改九宫格中的contentMode, 只是在显示图片的是 按照默认的contentMode显示的! 
举例: 
 在九宫格中显示的contentMode 是 UIViewContentModeCenter 类型, 可photoBrowser 中显示的样式肯定是 默认UIViewContentModeScaleToFill类型, 所以我这边可能没能理解你的意思!

**Comment by LuKane** [comment]
这个问题已经解决了!!! API中增加了 弹出动画的 contentModel 以及 图片展示时 ,图片的contentModel , 都做了区分
