### ISSUE TITLE
无法pod导入

### ISSUE THREAD

**Issue by jun-hui** [LuKane/KNPhotoBrowser#46]
warning: Could not find remote branch 2.0 to clone.
fatal: Remote branch 2.0 not found in upstream origin
请问这是什么原因呢

**Comment by LuKane** [comment]
最近 pod一直连不上! 过段时间再试试

**Comment by jun-hui** [comment]
好吧，那等两天我再试试看

**Comment by jun-hui** [comment]
不对哟，这个错应该不是pod的问题，我导其他三方都能正常导入的。而且下载下来的Demo一打开左侧文件一片红，而且podfile文件都没有

**Comment by LuKane** [comment]
我是说我这边的pod有问题!! 所以才会出现这样的事!!! 😆😆😆

**Comment by jun-hui** [comment]
哦，好的

**Comment by LuKane** [comment]
你这边用 2.4.6 即可
2.4.7没什么增加, 另外 2.4.7 pod上有问题, 找不到
