### ISSUE TITLE
视频播放页左滑时闪退

### ISSUE THREAD

**Issue by xphaijj** [LuKane/KNPhotoBrowser#49]
NSInvalidArgumentException: -[KNPhotoAVPlayerView playerWillSwipeCancel]: unrecognized selector sent to instance 0x103510710

**Comment by LuKane** [comment]
Demo闪退 还是 pod 中的闪退? 若是Demo, 请说下从哪个控制器进入的, 可以的话 说下 操作 .
若是 pod, 请说下 版本, 并附加代码和操作
