### ISSUE TITLE
预览的数组中只有一个视频的时候，左滑闪退

### ISSUE THREAD

**Issue by xphaijj** [LuKane/KNPhotoBrowser#50]
使用demo OR 最新的pod库   当只有一个网络视频预览时，左滑会闪退，
当只有一个视频时，uicollectionview是不能滚动的，这个时候会走到 panDidGesture 方法里面，会调用到 '-[KNPhotoAVPlayerView playerWillSwipeCancel]: 导致闪退

**Comment by LuKane** [comment]
我这边试了下!!!  Demo是没问题的!! pod库也没问题
注意: pod 最新版是2.5.2

**Comment by LuKane** [comment]
看了你邮件中发的代码, 有一个致命问题导致闪退
你的代码: 
`photoBrowser.itemsArr = @[self.itemsArr.firstObject];`

而正确的代码应该是:
`photoBrowser.itemsArr = [self.itemsArr copy];`

**Comment by xphaijj** [comment]
我知道   假如itemsArr 中只有一条数据时，就会出现异常，我只是为了在demo中演示出闪退的场景，所以直接修改了代码而已

**Comment by LuKane** [comment]
OK!,我再试试

**Comment by LuKane** [comment]
已经解决问题了! 多谢提出! 
pod版本为: 2.5.3
Demo已经更新!
