### ISSUE TITLE
图片加载有问题

### ISSUE THREAD

**Issue by JianWenXie** [LuKane/KNPhotoBrowser#53]
bundle中的图片，如果pod引入工程 ，图标显示不出来

**Comment by LuKane** [comment]
能具体说一下... 哪些图标不显示? 以及 在什么设备上测试的!! 我这边好对应修改!

**Comment by LuKane** [comment]
我这边试了一下 cocoapods.  bundle中的资源文件可以显示的!

**Comment by hstdt** [comment]
@LuKane  确实有图标显示不出来，pod导入的，视频按钮出不来

<img src="https://user-images.githubusercontent.com/10215098/147641717-d8a047b1-9365-4eef-bd65-2cb1fa623f88.jpeg" width="400">

**Comment by LuKane** [comment]
1.麻烦说一下 设备型号!!  
2.模拟器上能复现吗?

**Comment by hstdt** [comment]
> 1.麻烦说一下 设备型号 以及 系统版本号! 2.模拟器上能复现吗?

iPhone 8(iOS 13), iPhone XS Max(iOS 15) 和模拟器(iPad 11 IOS 15.2)均能复现

使用的是master分支代码

**Comment by LuKane** [comment]
方便的话. 加一下QQ细说!!  1169604556

**Comment by hstdt** [comment]
@LuKane  加载图片的代码增加一个in bundle就可以了

```
NSBundle *bundle = [NSBundle bundleForClass:[KNPhotoBrowser class]];
```

比如
```
- (void)setIsPlaying:(BOOL)isPlaying{
    _isPlaying = isPlaying;
    if (isPlaying) {
        _isDragging = false;
        [_slider setUserInteractionEnabled:true];

        [_pauseStopBtn setImage:[UIImage imageNamed:@"KNPhotoBrowser.bundle/pause@2x.png" inBundle:bundle compatibleWithTraitCollection:nil] forState:UIControlStateNormal];
    }else{
        [_pauseStopBtn setImage:[UIImage imageNamed:@"KNPhotoBrowser.bundle/play@2x.png" inBundle:bundle compatibleWithTraitCollection:nil] forState:UIControlStateNormal];
    }
}
```


另外使用asset就能更方便切换  1x 2x 3x 图


https://stackoverflow.com/a/61119321/4728060

**Comment by LuKane** [comment]
好的好的!!  我先找出部分机型显示不出来的原因

**Comment by hstdt** [comment]
> 好的好的!! 我先找出部分机型显示不出来的原因

@LuKane 就像上面说的，原因就是没加`inBundle`，加上就好了，我确认过了。

**Comment by LuKane** [comment]
好的

**Comment by LuKane** [comment]
可以试一下 !! cocoapods 2.5.5 版本!

**Comment by LuKane** [comment]
cocoapods中的 2.5.5版本已修复!
