### ISSUE TITLE
是否可以增加两个Delegate，在Pan手势开始、结束的时候触发

### ISSUE THREAD

**Issue by hstdt** [LuKane/KNPhotoBrowser#55]
微信下拉dismiss同时，会把底部按钮隐藏，直到松手。因此能否增加相对应的两个时间节点的手势呢。

**Comment by LuKane** [comment]
1.底部按钮 : 是指的哪些?? 
2.两个时间节点: 希望再明了一些, 我好修改修改

**Comment by hstdt** [comment]
@LuKane 

场景是这样的，需要自定义一些按钮，直接add到KNPhotoBrowser上。但是想要在pan手势开始和结束的时候，进行隐藏，类似于微信底部4个按钮那样的效果。

<img src="https://user-images.githubusercontent.com/10215098/147213795-9fdf2655-edde-4241-8b28-1cdabd13c09b.gif" width=40%/>

对应的在`panDidGesture`这里

**Comment by LuKane** [comment]
这个功能可以用指定的 API, Demo里也有
- (void)createCustomViewArrOnTopView:(NSArray<UIView *> *)customViewArr
                            animated:(BOOL)animated
                      followAnimated:(BOOL)followAnimated

**Comment by hstdt** [comment]
@LuKane 厉害了，原来是这个功能。我以为的customView是只支持完全替换掉现有View😅

**Comment by LuKane** [comment]
好的!! 下个版本的pod就这么改
