### ISSUE TITLE
2.5.4 Pod 添加的依赖找不到 bundle 中的图片资源

### ISSUE THREAD

**Issue by sjsurf** [LuKane/KNPhotoBrowser#58]

**Comment by LuKane** [comment]
用 2.5.5 Pod试试!!  方便的话, 把 2.5.5的bundle的图片资源 是否找到 和我说一下! 谢谢

**Comment by sjsurf** [comment]
可以获取到了，但是可能用Bundle来获取资源，会更简单一些

`- (UIImage*)loadImage:(NSString*)imageName {
    NSString *bundlePath = [[NSBundle bundleForClass:self.class].resourcePath stringByAppendingPathComponent:@"KNPhotoBrowser.bundle"];
    NSBundle *bundle = [NSBundle bundleWithPath:bundlePath];
    
    UIImage *image = [UIImage imageNamed:imageName inBundle:bundle compatibleWithTraitCollection:nil];
    return image;
}`

**Comment by LuKane** [comment]
我这边也是用的 bundle  
NSBundle *bundle = [NSBundle bundleForClass:NSClassFromString(@"KNPhotoBrowser")];

**Comment by sjsurf** [comment]
哈，就是之前拿了之前的demo的代码，我看你2.5.5读资源是根据scale区分了图片的名称。
`UIImage *image = [UIImage imageNamed:imageName inBundle:bundle compatibleWithTraitCollection:nil];
return image;`我之前看文档是会根据设备型号自动区分的。

**Comment by LuKane** [comment]
那个好像类似于  Assets.xcassets 功能!! 我这边只做了个简单的实现!
