### ISSUE TITLE
视频播放没声音...

### ISSUE THREAD

**Issue by SnailLoveSmile** [LuKane/KNPhotoBrowser#66]
感谢lukane哥 提供的这个优秀的框架, 今天 下载demo 视频播放发现 如果将photoBrowser.isNeedOnlinePlay = false;
   改为false, 视频会没有声音. 手机iphone6s 14.7.1 系统,  另外iphonex 16的系统也是如此

**Comment by LuKane** [comment]
啊~ 四国一!  我这边试试

**Comment by LuKane** [comment]
试下刚刚上传的 pod 2.6.2 的版本!! 我这边在Demo中试了下, 是可以的了. 若你那边没问题的话, 验证过后, 记得关下这个 issue 😊😊

**Comment by SnailLoveSmile** [comment]
> 试下刚刚上传的 pod 2.6.2 的版本!! 我这边在Demo中试了下, 是可以的了. 若你那边没问题的话, 验证过后, 记得关下这个 issue 😊😊

嗯嗯, 非常感谢, 如此神速的改掉了这个问题, 谢谢.再次谢谢

**Comment by LuKane** [comment]
你给这个小架子提出bug, 应该是我谢谢你才对!!  😄😄
