### ISSUE TITLE
是否能当成View来使用

### ISSUE THREAD

**Issue by kuronekomimi** [LuKane/KNPhotoBrowser#67]
发现是继承UIViewController，想当成View来使用，然后再增加一个刷新数据源的功能就好了

**Comment by LuKane** [comment]
1.这个小架子初期是用 UIView来做的, 但是考虑到 屏幕旋转等功能, 还是修改成 UIViewController来做了! 
2.关于您提出的 刷新数据源的功能, 是想如何去 刷新? 详细一点, 我这边好着手

**Comment by kuronekomimi** [comment]
比如重新赋值itemsArr，想刷新一下当前图片数据

**Comment by LuKane** [comment]
你的意思是:  在浏览器已经展示的同时, 可以修改 数据源 刷新当前 浏览器哈!! 
好的. 这个需求还挺好. 我这几天改好后 会在这里告诉一下

**Comment by LuKane** [comment]
代码已经更新了 刷新机制! 
cocoapods 暂没更新

**Comment by LuKane** [comment]
KNPhotoBrowser.h 文件中  267行 新增:
- (void)reloadDataWithCurrentIndex:(NSInteger)currentIndex;
